name: CI

on:
  push:
    branches:
      - iris4.0
  pull_request:
    branches:
      - "**"
  schedule:
    # every day at 11am UTC (6am EST)
    - cron: "0 11 * * *"
  workflow_dispatch:

jobs:
  build-release:
    name: build (released iris, coq latest)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: coq-community/docker-coq-action@v1
        with:
          custom_image: "coqorg/coq:latest"
# See also:
# https://github.com/coq-community/docker-coq-action#readme
# https://github.com/erikmd/docker-coq-github-action-demo
